version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser"
  ]
  style_guide = "airbnb"
  skip_doc_coverage = ["file-paths"]

  # Ignore JSX maximum depth validation (JS-0415)
  # We've already extracted components where appropriate.
  # Further extraction would have diminishing returns.
  [[analyzers.meta.exclude]]
  patterns = ["JS-0415"]

[[analyzers]]
name = "rust"
enabled = true

# Disabled until tests are implemented
# [[analyzers]]
# name = "test-coverage"
# enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "rustfmt"
enabled = true
